using 'apps.bicep'

param location = 'swedencentral'
param acrname = 'acrjkacademo'
param storageName = 'stjkacademo'
param storagedaprname = 'mystorage'
param kvname = 'kv-aca-demo240208'
param kvdaprname = 'mysecretstore'
param acaEnvName = 'acaenvdemo'
param ainame = 'ai-academo'
param secretname = 'mysecret'
param secretvalue = 'abc123'
param externalapiversion = '0.9'
param internalapiversion = '0.9'
