using 'infra.bicep'

param acrname = 'acrjkacademo'
param lawname = 'lajkacademo'
param envname = 'acaenvdemo'
param ainame = 'ai-academo'
param vnetname = 'acavnet'
param vnetPrefix = '192.168.0.0/23'
param acaSubnetName = 'acasubnet'
param acaSubnetPrefix = '192.168.0.0/26'
param appgwSubnetName = 'appgwsubnet'
param appgwSubnetPrefix = '192.168.1.0/26'
// param appgwname = 'appgw-aca-demo'
